title: anuree
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: anuree
tagline: anuree thayarat
about-description: # Add Discription
pic: https://rr.img.naver.jp/mig?src=http%3A%2F%2Fimgcc.naver.jp%2Fkaze%2Fmission%2FUSER%2F20150310%2F42%2F4502692%2F21%2F630x630x443eab804423cc72b961d53d.jpg%2F300%2F600&twidth=300&theight=600&qlt=80&res_format=jpg&op=r  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: anuree.tcs57@ubru.ac.th # Add your Email address
phone: 0853045150 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
